#!/bin/bash

# This script is shamelessly adapted from https://github.com/saalfeldlab/n5-utils, thanks @axtimwalde & co!

VERSION="0.1.0-SNAPSHOT"
INSTALL_DIR=${1:-$(pwd)}

echo ""
echo "Installing into $INSTALL_DIR"

# check for operating system
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  echo "Assuming on Linux operating system"
  MEM=$(cat /proc/meminfo | grep MemTotal | sed s/^MemTotal:\\\s*\\\|\\\s\\+[^\\\s]*$//g)
  MEMGB=$(($MEM/1024/1024))
  MEM=$((($MEMGB/5)*4))
elif [[ "$OSTYPE" == "darwin"* ]]; then
  echo "Assuming on MacOS X operating system"
  # sysctl returns total hardware memory size in bytes
  MEM=$(sysctl hw.memsize | grep hw.memsize | sed s/hw.memsize://g)
  MEMGB=$(($MEM/1024/1024/1024))
  MEM=$((($MEMGB/5)*4))
else
  echo "ERROR - Operating system (arg2) must be either linux or osx - EXITING (on windows please run as a normal Java class from e.g. Eclipse)"
  exit
fi

echo "Available memory:" $MEMGB "GB, setting Java memory limit to" $MEM "GB"

mvn clean install
mvn -Dmdep.outputFile=cp.txt -Dmdep.includeScope=runtime dependency:build-classpath

echo ""
echo "Installing 'st-explorer' command into" $INSTALL_DIR
echo ""

echo '#!/bin/bash' > st-explorer
echo '' >> st-explorer
echo "JAR=\$HOME/.m2/repository/net/preibisch/imglib2-st/${VERSION}/imglib2-st-${VERSION}.jar" >> st-explorer
echo 'java \' >> st-explorer
echo "  -Xmx${MEM}g \\" >> st-explorer
echo '  -XX:+UseConcMarkSweepGC \' >> st-explorer
echo -n '  -cp $JAR:' >> st-explorer
echo -n $(cat cp.txt) >> st-explorer
echo ' \' >> st-explorer
echo '  cmd.View "$@"' >> st-explorer


echo "Installing 'st-render' command into" $INSTALL_DIR
echo ""

echo '#!/bin/bash' > st-render
echo '' >> st-render
echo "JAR=\$HOME/.m2/repository/net/preibisch/imglib2-st/${VERSION}/imglib2-st-${VERSION}.jar" >> st-render
echo 'java \' >> st-render
echo "  -Xmx${MEM}g \\" >> st-render
echo '  -XX:+UseConcMarkSweepGC \' >> st-render
echo -n '  -cp $JAR:' >> st-render
echo -n $(cat cp.txt) >> st-render
echo ' \' >> st-render
echo '  cmd.RenderImage "$@"' >> st-render


echo "Installing 'st-bdv-view' command into" $INSTALL_DIR
echo ""

echo '#!/bin/bash' > st-bdv-view
echo '' >> st-bdv-view
echo "JAR=\$HOME/.m2/repository/net/preibisch/imglib2-st/${VERSION}/imglib2-st-${VERSION}.jar" >> st-bdv-view
echo 'java \' >> st-bdv-view
echo "  -Xmx${MEM}g \\" >> st-bdv-view
echo '  -XX:+UseConcMarkSweepGC \' >> st-bdv-view
echo -n '  -cp $JAR:' >> st-bdv-view
echo -n $(cat cp.txt) >> st-bdv-view
echo ' \' >> st-bdv-view
echo '  cmd.DisplayStackedSlides "$@"' >> st-bdv-view


echo "Installing 'st-resave' command into" $INSTALL_DIR
echo ""

echo '#!/bin/bash' > st-resave
echo '' >> st-resave
echo "JAR=\$HOME/.m2/repository/net/preibisch/imglib2-st/${VERSION}/imglib2-st-${VERSION}.jar" >> st-resave
echo 'java \' >> st-resave
echo "  -Xmx${MEM}g \\" >> st-resave
echo '  -XX:+UseConcMarkSweepGC \' >> st-resave
echo -n '  -cp $JAR:' >> st-resave
echo -n $(cat cp.txt) >> st-resave
echo ' \' >> st-resave
echo '  cmd.Resave "$@"' >> st-resave

echo "Installing 'st-normalize' command into" $INSTALL_DIR
echo ""

echo '#!/bin/bash' > st-normalize
echo '' >> st-normalize
echo "JAR=\$HOME/.m2/repository/net/preibisch/imglib2-st/${VERSION}/imglib2-st-${VERSION}.jar" >> st-normalize
echo 'java \' >> st-normalize
echo "  -Xmx${MEM}g \\" >> st-normalize
echo '  -XX:+UseConcMarkSweepGC \' >> st-normalize
echo -n '  -cp $JAR:' >> st-normalize
echo -n $(cat cp.txt) >> st-normalize
echo ' \' >> st-normalize
echo '  cmd.Normalize "$@"' >> st-normalize


echo "Installing 'st-align-pairs' command into" $INSTALL_DIR
echo ""

echo '#!/bin/bash' > st-align-pairs
echo '' >> st-align-pairs
echo "JAR=\$HOME/.m2/repository/net/preibisch/imglib2-st/${VERSION}/imglib2-st-${VERSION}.jar" >> st-align-pairs
echo 'java \' >> st-align-pairs
echo "  -Xmx${MEM}g \\" >> st-align-pairs
echo '  -XX:+UseConcMarkSweepGC \' >> st-align-pairs
echo -n '  -cp $JAR:' >> st-align-pairs
echo -n $(cat cp.txt) >> st-align-pairs
echo ' \' >> st-align-pairs
echo '  cmd.PairwiseSectionAligner "$@"' >> st-align-pairs


echo "Installing 'st-align-pairs-view' command into" $INSTALL_DIR
echo ""

echo '#!/bin/bash' > st-align-pairs-view
echo '' >> st-align-pairs-view
echo "JAR=\$HOME/.m2/repository/net/preibisch/imglib2-st/${VERSION}/imglib2-st-${VERSION}.jar" >> st-align-pairs-view
echo 'java \' >> st-align-pairs-view
echo "  -Xmx${MEM}g \\" >> st-align-pairs-view
echo '  -XX:+UseConcMarkSweepGC \' >> st-align-pairs-view
echo -n '  -cp $JAR:' >> st-align-pairs-view
echo -n $(cat cp.txt) >> st-align-pairs-view
echo ' \' >> st-align-pairs-view
echo '  cmd.ViewPairwiseAlignment "$@"' >> st-align-pairs-view

echo "Installing 'st-align-global' command into" $INSTALL_DIR
echo ""

echo '#!/bin/bash' > st-align-global
echo '' >> st-align-global
echo "JAR=\$HOME/.m2/repository/net/preibisch/imglib2-st/${VERSION}/imglib2-st-${VERSION}.jar" >> st-align-global
echo 'java \' >> st-align-global
echo "  -Xmx${MEM}g \\" >> st-align-global
echo '  -XX:+UseConcMarkSweepGC \' >> st-align-global
echo -n '  -cp $JAR:' >> st-align-global
echo -n $(cat cp.txt) >> st-align-global
echo ' \' >> st-align-global
echo '  cmd.GlobalOpt "$@"' >> st-align-global


chmod a+x st-explorer
chmod a+x st-bdv-view
chmod a+x st-render
chmod a+x st-resave
chmod a+x st-normalize
chmod a+x st-align-pairs
chmod a+x st-align-pairs-view
chmod a+x st-align-global

if [ $(pwd) == "$INSTALL_DIR" ]; then
    echo "Installation directory equals current directory, we are done."
else
	echo "Creating directory $INSTALL_DIR and moving files..."
    mkdir -p $INSTALL_DIR
    mv st-explorer $INSTALL_DIR/
    mv st-bdv-view $INSTALL_DIR/
    mv st-render $INSTALL_DIR/
    mv st-resave $INSTALL_DIR/
    mv st-normalize $INSTALL_DIR/
fi

rm cp.txt

echo "Installation finished."
